# ~/.agents/skills is a well-known location agent skills.
# eventough I'd prefer ~/.config/agents/skills
# Moreover, symblic skills are not discoverable by codex
# then it's suggested to maintain your own skills physicall in ~/.agents
# which is a most generic soluton for major coding clis.

[creating-slides.files]
'skills/creating-slides' = '~/.config/agents/skills/creating-slides'

[fetching-onenote-wiki.files]
'skills/fetching-onenote-wiki' = '~/.config/agents/skills/fetching-onenote-wiki'

[generating-images.files]
'skills/generating-images' = '~/.config/agents/skills/generating-images'

[researching-deeply.files]
'skills/researching-deeply' = '~/.config/agents/skills/researching-deeply'

[researching-widely.files]
'skills/researching-widely' = '~/.config/agents/skills/researching-widely'

[using-typst.files]
'skills/using-typst' = '~/.config/agents/skills/using-typst'

[writing-reports.files]
'skills/writing-reports' = '~/.config/agents/skills/writing-reports'

# Meta Packages
[research-skills]
depends = ['researching-deeply', 'researching-widely']

[doc-skills]
depends = ['creating-slides', 'using-typst', 'writing-reports']

[default]
depends = [
  'creating-slides',
  'fetching-onenote-wiki',
  'generating-images',
  'researching-deeply',
  'researching-widely',
  'using-typst',
  'writing-reports',
]
